logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG


spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 12345
    url: jdbc:mysql://localhost:3306/daily_nail_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        generate_statistics: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
    resources:
      static-locations: "classpath:/static/"



cloudinary:
  cloud-name: dzjgi2c7y
  api-key: 459312976342331
  api-secret: "${CLOUDINARY_SECRET}"